dbMemo "SQL" ="SELECT [StudyAreas].[StudyAreaAbbr] & \" - \" & [CameraLocations].[LocationName]"
    " AS Location, CameraLocations.StudyAreaID, SetVisits.VisitDate, CameraLocations."
    "UTM_E, CameraLocations.UTM_N, CameraLocations.AccessNotes, SetVisits.LocationID\015"
    "\012FROM ((StudyAreas INNER JOIN CameraLocations ON StudyAreas.StudyAreaID = Cam"
    "eraLocations.StudyAreaID) INNER JOIN Visits AS SetVisits ON CameraLocations.Loca"
    "tionID = SetVisits.LocationID) LEFT JOIN (SELECT SetVisitID FROM Visits WHERE (("
    "(VisitTypeID)=2)))  AS PullVisits ON SetVisits.VisitID = PullVisits.SetVisitID\015"
    "\012WHERE (((SetVisits.VisitTypeID)=3) AND ((PullVisits.SetVisitID) Is Null));\015"
    "\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbByte "RecordsetType" ="0"
dbBoolean "TotalsRow" ="0"
Begin
End
