CREATE TABLE [DetailShortcuts] (
  [DetailID] LONG  CONSTRAINT [{04B5E5FF-0896-4391-8238-6E68199ADD59}] UNIQUE REFERENCES [DetectionDetails] ([DetailID]) ON UPDATE CASCADE  ON DELETE CASCADE  CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Shortcut] VARCHAR (1)
)
