CREATE TABLE [DetectionDetails] (
  [DetailID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [DetailText] VARCHAR (255),
  [SpeciesID] LONG  CONSTRAINT [{B029EB56-894B-4EA8-9164-C72FCB3A4570}] REFERENCES [Species] ([SpeciesID]) ON UPDATE CASCADE  ON DELETE CASCADE 
)
