CREATE TABLE [IndependentDetections] (
  [IndDetectionID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [SpeciesID] LONG  CONSTRAINT [{7E8ED7F2-6E58-452D-BBDC-9237ED744B50}] REFERENCES [Species] ([SpeciesID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [LocationID] LONG  CONSTRAINT [{1F082F31-01BC-4BA5-A3E3-0D4F65A7F882}] REFERENCES [CameraLocations] ([LocationID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [DefaultStart] DATETIME ,
  [ModifiedStart] DATETIME ,
  [Deleted] BIT 
)
