CREATE TABLE [Individuals] (
  [IndividualID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [IndividualName] VARCHAR (14),
  [SpeciesID] LONG  CONSTRAINT [{9EC1C8D0-1C74-484B-817F-CB70F9B8FAC4}] REFERENCES [Species] ([SpeciesID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [GenderID] LONG  CONSTRAINT [{BF1AC7DE-285C-46CD-83CA-59DABDF641A4}] REFERENCES [lkupGender] ([GenderID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [Comments] VARCHAR (255),
  [ReferencePhoto1] VARCHAR (255),
  [ReferencePhoto2] VARCHAR (255)
)
