CREATE TABLE [ObsPhone] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [ObserverID] LONG  CONSTRAINT [{715E04DE-0BF0-4B1D-8A71-BE2D0B8B601A}] REFERENCES [Observers] ([ObserverID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [TypeID] LONG ,
  [PhoneNumber] VARCHAR (10),
  [Extension] VARCHAR (10)
)
