CREATE TABLE [PhotoTags] (
  [TagID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [TagX] DOUBLE ,
  [TagY] DOUBLE ,
  [XLen] DOUBLE ,
  [YLen] DOUBLE ,
  [ImageID] LONG  CONSTRAINT [PhotosPhotoTags] REFERENCES [Photos] ([ImageID]) ON UPDATE CASCADE  ON DELETE CASCADE ,
  [ObsID] LONG 
)
