CREATE TABLE [SpeciesShortcuts] (
  [SpeciesID] LONG  CONSTRAINT [{CF7B6855-0F8D-4E67-B78E-24F0617E2F8B}] UNIQUE REFERENCES [Species] ([SpeciesID]) ON UPDATE CASCADE  ON DELETE CASCADE  CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Shortcut] VARCHAR (1)
)
